# Generated by Django 6.0.1 on 2026-01-21 04:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mobile', models.TextField(blank=True, help_text='Used for 2FA and Alert management', null=True, verbose_name='SMS/Mobile Number')),
                ('acctnum_prefix', models.TextField(blank=True, null=True, verbose_name='Manager Account Prefix')),
                ('must_change_pw', models.BooleanField(default=True)),
                ('must_set_tz', models.BooleanField(default=True)),
                ('enable_history_log', models.BooleanField(default=True)),
                ('win_notification_threshold', models.IntegerField(default=500)),
            ],
        ),
    ]
