# Generated by Django 6.0.1 on 2026-01-21 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('parameters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.vhostdomain'),
        ),
        migrations.AddField(
            model_name='manager',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.locales', verbose_name='Account Locale'),
        ),
        migrations.AddField(
            model_name='manager',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_parent', to=settings.AUTH_USER_MODEL, verbose_name='Parent User/Agent'),
        ),
        migrations.AddField(
            model_name='manager',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.timezone', verbose_name='Account Timezone'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='User/Manager Name'),
        ),
        migrations.AddField(
            model_name='manager',
            name='vhost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('user', 'vhost', 'domain')},
        ),
    ]
