# Generated by Django 5.1 on 2025-09-21 18:30
import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0001_initial'),
        ('parameters', '0058_alter_apperanceparameters_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amfgame',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amfgameevent',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amfgameplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amfgamescore',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amfplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babgame',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babgameevent',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babgameplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babgamescore',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basegame',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basegameevent',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basegameplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basegamescore',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coresportmap',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fballgame',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fballgamescore',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fballplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hockgame',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hockgameevent',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, related_name='as_hock', to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hockgameplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hockgamescore',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hockplayerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, related_name='as_league', to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstats',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, related_name='as_season', to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamleagues',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamvenue',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='vhost',
            field=models.ForeignKey(default=uuid.UUID('11fc00c3-53d1-4b08-ae4e-cf62e2985d0e'), on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
    ]
