# Generated by Django 5.1 on 2025-09-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0002_amfgame_vhost_amfgameevent_vhost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockgamescore',
            name='second',
            field=models.IntegerField(null=True),
        ),
    ]
