# Generated by Django 5.1 on 2025-11-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0003_hockgamescore_second'),
        ('parameters', '0183_alter_timezone_options'),
        ('sports', '0002_country_vhost_group_vhost_season_vhost_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amfgameplayerstats',
            unique_together={('player', 'season', 'group', 'name', 'amf_game', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='amfgamescore',
            unique_together={('match', 'team', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='amfplayerstats',
            unique_together={('player', 'season', 'group', 'name', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='babgamescore',
            unique_together={('match', 'team', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='basegameplayerstats',
            unique_together={('player', 'season', 'group', 'name', 'base_game', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='basegamescore',
            unique_together={('match', 'team', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='coresportmap',
            unique_together={('sport', 'league', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='fballgamescore',
            unique_together={('match', 'team', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='fballplayerstats',
            unique_together={('player', 'team', 'league', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='hockgameplayerstats',
            unique_together={('player', 'season', 'group', 'name', 'hock_game', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='hockgamescore',
            unique_together={('match', 'team', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='hockplayerstats',
            unique_together={('player', 'season', 'group', 'name', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('id', 'sport_mask', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('id', 'league', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('player', 'season', 'group', 'name', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('id', 'sport_mask', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='teamleagues',
            unique_together={('team', 'league', 'sport_mask', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='teamvenue',
            unique_together={('team', 'venue', 'vhost')},
        ),
    ]
