# Generated by Django 5.2.6 on 2025-11-25 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0003_hockgamescore_second'),
        ('parameters', '0183_alter_timezone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMFGameScoreSummary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.amfgame')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='BABGameScoreSummary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.babgame')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='BASEGameScoreSummary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.basegame')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='FBALLGameScoreSummary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.fballgame')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='HOCKGameScoreSummary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.hockgame')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='apisports.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost')),
            ],
        ),
    ]
