# Generated by Django 5.1 on 2025-11-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0004_alter_amfgameplayerstats_unique_together_and_more'),
        ('parameters', '0183_alter_timezone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfgame',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='babgame',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basegame',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fballgame',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hockgame',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(verbose_name='API Player ID'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.IntegerField(verbose_name='API Venue ID'),
        ),
        migrations.AlterUniqueTogether(
            name='amfgame',
            unique_together={('id', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='babgame',
            unique_together={('id', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='basegame',
            unique_together={('id', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='fballgame',
            unique_together={('id', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='hockgame',
            unique_together={('id', 'vhost')},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('id', 'vhost')},
        ),
    ]
