# Generated by Django 5.2.6 on 2025-11-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0004_amfgamescoresummary_babgamescoresummary_and_more'),
        ('apisports', '0005_alter_amfgame_id_alter_babgame_id_alter_basegame_id_and_more'),
    ]

    operations = [
    ]
