# Generated by Django 5.2.6 on 2025-12-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0006_merge_20251125_1605'),
        ('apisports', '0006_merge_20251130_1410'),
    ]

    operations = [
    ]
