# Generated by Django 5.2.6 on 2025-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0007_merge_20251201_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Country Flag'),
        ),
    ]
