# Generated by Django 5.2.6 on 2025-12-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0007_merge_20251130_1908'),
        ('apisports', '0008_alter_team_flag'),
    ]

    operations = [
    ]
