# Generated by Django 6.0.1 on 2026-01-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisports', '0009_merge_0007_merge_20251130_1908_0008_alter_team_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='season_override',
            field=models.TextField(blank=True, null=True, verbose_name='Season value override'),
        ),
    ]
