# Generated by Django 6.0.1 on 2026-01-21 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerNotifications',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Bonus Level Name')),
                ('active', models.BooleanField(default=True)),
                ('title', models.TextField(verbose_name='Title')),
                ('type', models.TextField(default='not', verbose_name='Type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Seen At:')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Icon')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountNotifications',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Bonus Level Name')),
                ('active', models.BooleanField(default=True)),
                ('title', models.TextField(verbose_name='Title')),
                ('type', models.TextField(default='not', verbose_name='Type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Seen At:')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Icon')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.account')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
