# Generated by Django 6.0.1 on 2026-01-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_initial'),
        ('notifications', '0001_initial'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnotifications',
            name='vdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.vhostdomain'),
        ),
        migrations.AddField(
            model_name='accountnotifications',
            name='vhost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
        ),
        migrations.AddField(
            model_name='managernotifications',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.manager'),
        ),
        migrations.AddField(
            model_name='managernotifications',
            name='vdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.vhostdomain'),
        ),
        migrations.AddField(
            model_name='managernotifications',
            name='vhost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
        ),
    ]
