# Generated by Django 6.0.1 on 2026-01-29 22:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsGroupView',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('group_slug', models.SlugField()),
                ('group_name', models.TextField()),
                ('group_icon', models.TextField()),
                ('sport_key', models.TextField()),
                ('sport_title', models.TextField()),
                ('sport_card_logo', models.FileField(upload_to='')),
                ('sport_large_logo', models.FileField(upload_to='')),
                ('sport_description', models.TextField()),
                ('sport_featured', models.BooleanField()),
            ],
            options={
                'db_table': 'sports_sport_group_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('icon', models.CharField(blank=True, null=True, verbose_name='Font Awesome Icon')),
                ('flag', models.FileField(blank=True, null=True, upload_to='', verbose_name='Country Flag')),
                ('name', models.CharField(verbose_name='Country Name')),
                ('code', models.CharField(verbose_name='Country Code')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ath_countries', to='parameters.vhost')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'vhost')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Group Slug')),
                ('icon', models.CharField(blank=True, null=True, verbose_name='Icon (use HTML!)')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Sport Group Name')),
                ('generic_icon', models.CharField(blank=True, help_text='Will be used for sports leagues that do not have a custom icon.', null=True, verbose_name='Generic FA Icon')),
                ('card_trending_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Trending Card Image')),
                ('has_periods', models.BooleanField(default=False, verbose_name='Does the Sport Group have Period-based Props (for display in sportsbook)')),
                ('has_teasers', models.BooleanField(default=False, verbose_name='Does the Sport group have Teaser bets')),
                ('teaser_pts_mask', models.CharField(blank=True, null=True, verbose_name='Mask for selecting the points in Teaser bets (hint: amf, bab..) just like core sports maps.')),
                ('bookmaker_uses_own_template', models.BooleanField(default=False, verbose_name='Bookmaker uses own template File for Lines')),
                ('active', models.BooleanField(default=True)),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ath_groups', to='parameters.vhost')),
            ],
            options={
                'ordering': ['slug'],
                'unique_together': {('name', 'vhost')},
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('season_key', models.CharField(default='', help_text='Season key (YYYY)', verbose_name='Season Key')),
                ('name', models.CharField(verbose_name='Season Name')),
                ('active', models.BooleanField(default=True)),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ath_seasons', to='parameters.vhost')),
            ],
            options={
                'ordering': ['-season_key'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.TextField(verbose_name='Key')),
                ('apisport_id', models.CharField(blank=True, db_index=True, help_text='API Sport ID', null=True, verbose_name='API Sport ID')),
                ('apitennis_id', models.CharField(blank=True, db_index=True, help_text='API Sport ID', null=True, verbose_name='API Sport ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('card_logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sports/League Logo for UI')),
                ('large_logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sports/League Large Logo for UI')),
                ('description', models.TextField(verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('has_outrights', models.BooleanField(default=True, verbose_name='Has Outrights')),
                ('has_wagers', models.BooleanField(default=True, verbose_name='Has Wagers')),
                ('skip_index_display', models.BooleanField(default=False, verbose_name='Skip this League in the Sports index view.')),
                ('featured', models.BooleanField(default=False, help_text="Featured leagues show up in a separate tab in the player's ui.", verbose_name='Featured')),
                ('priority', models.IntegerField(default=0, help_text='Feature/Order Priority (lowest first)', verbose_name='Priority #')),
                ('wager_limit', models.IntegerField(default=10000, help_text='Maximum Wager allowed in this sport/league', verbose_name='Max Wager Limit')),
                ('min_wager', models.IntegerField(default=100, help_text='Minimum Wager allowed in this sport/league', verbose_name='Min Wager Limit')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sports.country', verbose_name='League Country')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sports.group', verbose_name='Sport Grouping')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sports.season', verbose_name='Season')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ath_sports', to='parameters.vhost')),
            ],
            options={
                'ordering': ['key', 'priority'],
            },
        ),
    ]
