# Generated by Django 5.1 on 2025-09-01 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0035_alter_accountactivationtokens_key_and_more'),
        ('parameters', '0035_alter_vhostfrontendapperanceparameters_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('draw_date', models.DateField()),
                ('draw_datetime', models.DateTimeField(blank=True, null=True)),
                ('draw_number', models.CharField(blank=True, max_length=50, null=True)),
                ('main_numbers', models.JSONField(default=list)),
                ('bonus_numbers', models.JSONField(default=list)),
                ('multiplier', models.IntegerField(blank=True, null=True)),
                ('jackpot_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('jackpot_currency', models.CharField(default='USD', max_length=10)),
                ('next_jackpot', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('next_draw_date', models.DateField(blank=True, null=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='LotteryTicketCheck',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_main_numbers', models.JSONField(default=list)),
                ('user_bonus_number', models.IntegerField(blank=True, null=True)),
                ('user_multiplier', models.BooleanField(default=False)),
                ('main_matches', models.IntegerField(default=0)),
                ('bonus_match', models.BooleanField(default=False)),
                ('prize_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('lottery_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_checks', to='collectapi.lotterydraw')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('api_endpoint', models.CharField(max_length=200)),
                ('checker_endpoint', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost')),
            ],
            options={
                'unique_together': {('vhost', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='lotterydraw',
            name='lottery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='collectapi.lotterytype'),
        ),
        migrations.CreateModel(
            name='LotterySyncStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('last_sync', models.DateTimeField()),
                ('last_draw_date', models.DateField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sync_count', models.IntegerField(default=0)),
                ('lottery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectapi.lotterytype')),
            ],
            options={
                'unique_together': {('lottery_type',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lotterydraw',
            unique_together={('lottery_type', 'draw_date')},
        ),
    ]
