# Generated by Django 5.1 on 2025-09-20 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectapi', '0001_initial'),
        ('parameters', '0056_alter_apperanceparameters_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryPayoutConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('multiplier', models.IntegerField(default=10000, help_text='Payout multiplier for exact match (e.g., 10000 = 10,000x)')),
                ('max_payout', models.DecimalField(decimal_places=2, default=100000, help_text='Maximum payout amount', max_digits=10)),
                ('min_wager', models.DecimalField(decimal_places=2, default=1, help_text='Minimum wager amount', max_digits=10)),
                ('max_wager', models.DecimalField(decimal_places=2, default=100, help_text='Maximum wager amount', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lottery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectapi.lotterytype')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost')),
            ],
            options={
                'unique_together': {('vhost', 'lottery_type')},
            },
        ),
    ]
