"""
Django settings for GDL project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import zoneinfo
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from decouple import Config, RepositoryEnv, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CONFIG_FILE = os.getenv("CONFIG_FILE")

# Load ENV config override
# Load config preferentially from /config/settings.ini first! .env if it fails.
config = False
if CONFIG_FILE:
    config_path = f"{CONFIG_FILE}"
    if os.path.exists(config_path):
        config = Config(RepositoryEnv(f'{CONFIG_FILE}'))
    else:
        config = False
        print(f"WARNING: Specified config file [{CONFIG_FILE}] does not exist")
if not config:
    if os.path.isdir(f"{BASE_DIR}/config") and os.path.isfile(f"{BASE_DIR}/config/settings.ini"):
        config = Config(RepositoryEnv(f'{BASE_DIR}/config/settings.ini'))
    elif os.path.isfile(f"{BASE_DIR}/settings.ini"):
        config = Config(RepositoryEnv(f'{BASE_DIR}/settings.ini'))
    else:
        config = Config(RepositoryEnv(f'{BASE_DIR}/.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY","django-insecure-d+fzn25e#eg^z8+w7!oq-oqu6xl7rfip%mo$=o+e_42(v8najq")
DEBUG = config("ENABLE_DEBUG",False,cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS","127.0.0.1,192.168.1.188,*",cast=Csv())


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "grappelli",
    "corsheaders",
    "modeltranslation",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",
    "django_bootstrap5",
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_email',  # <- if you want email capability.
    'two_factor',
    'two_factor.plugins.phonenumber',  # <- if you want phone number capability.
    'two_factor.plugins.email',
    "mathfilters",
    "rest_framework",
    "account",
    "parameters",
    "notifications",
    "management",
    "cashier",
    "sports",
    "matches",
    "odds",
    "outcomes",
    "wager",
    "minerve",
    "teams",
    "licensemanager",
    "players",
    "dataengine",
    "game.gdlcore",
    "game.gdlfront",
    "game.gdlmanagement",
    "gdl"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gdl.middleware.account_context.AccountContextMiddleware'
]

ROOT_URLCONF = 'gdl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [
            BASE_DIR / "static",  # 👈 THIS IS THE FIX
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CHANNEL_LAYERS = {
    "default": {
        "CONFIG": {
            "hosts": [(config("CHANNEL_REDIS_HOST","127.0.0.1"), config("CHANNEL_REDIS_PORT","6379"))],
        },
        "BACKEND": "channels_redis.core.RedisChannelLayer",
    },
}
WSGI_APPLICATION = 'gdl.wsgi.application'


# Database

def pg_db(
    *,
    name,
    user,
    password,
    host,
    port,
    engine="django.db.backends.postgresql",
    conn_max_age=600,
    options=None,
    test_name=None,
):
    db = {
        "ENGINE": engine,
        "NAME": name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": port,
        "CONN_MAX_AGE": conn_max_age,
    }

    if options:
        db["OPTIONS"] = options

    if test_name:
        db["TEST"] = {"NAME": test_name}

    return db

DATABASES = {}

# ------------------------
# Core (default / replica)
# ------------------------

DATABASES["default"] = pg_db(
    engine=config("DB_ENGINE", "django.db.backends.postgresql"),
    name=config("DB_NAME", "GDL"),
    user=config("DB_USER", "GDL"),
    password=config("DB_PW", "supersecret"),
    host=config("DB_HOST", "localhost"),
    port=config("DB_PORT", 5432),
    conn_max_age=0,
    options={"connect_timeout":  5},
)

DB_REPLICA_PORT = config("DB_REPLICA_PORT", default=None)
if DB_REPLICA_PORT:
    DATABASES["replica"] = {
        **DATABASES["default"],
        "PORT": DB_REPLICA_PORT,
    }

DATABASE_ROUTERS = config("DATABASE_ROUTERS", cast=Csv(),default="")
if DB_REPLICA_PORT and DATABASE_ROUTERS == []:
    DATABASE_ROUTERS = ['gdl.db_routers.PrimaryReplicaRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGES = [
    ('en', _('English')),
    ('es', _('Spanish')),
    ('fr','French'),
    ('pt','Portuguese'),
]
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
LANGUAGE_CODE = config("LANGUAGE_CODE","en-ca")

TIME_ZONE = config("TIME_ZONE","America/Los_Angeles")
USE_I18N = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

USE_TZ = True
TZ = zoneinfo.ZoneInfo(TIME_ZONE)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",                 # Django-managed
    BASE_DIR / "static/frontend",         # Vite output
]

STATIC_ROOT = BASE_DIR / "staticfiles"   #

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": config("REDIS_CACHE_LOCATION","redis://127.0.0.1:6379"),
    }
}
USE_LOCAL_MEDIA = config("USE_LOCAL_MEDIA",False,cast=bool)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 30 * 60
EMAIL_BACKEND=config("EMAIL_BACKEND","django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST=config("EMAIL_HOST","localhost")
EMAIL_PORT=config("EMAIL_PORT",587)
EMAIL_HOST_USER=config("EMAIL_HOST_USER","username")
EMAIL_HOST_PASSWORD=config("EMAIL_HOST_PASSWORD","password")
EMAIL_USE_TLS = config("EMAIL_USE_TLS",False,cast=bool)
EMAIL_FROM_ADDR=config("EMAIL_FROM_ADDR","no-reply@localhost")
EMAIL_REPLY_TO=config("EMAIL_REPLY_TO","no-reply@localhost")
CSRF_TRUSTED_ORIGINS=config("CSRF_TRUSTED_ORIGINS",None,cast=Csv())
CORS_ALLOWED_ORIGINS=config("CORS_ALLOWED_ORIGINS",None,cast=Csv())
FONT_AWESOME_KIT = "52b95d724a.js"
ALLOWED_HOSTS = config("ALLOWED_HOSTS","127.0.0.1,192.168.1.188,*",cast=Csv())
ROOT_URLCONF = config("ROOT_URLCONF","gdl.urls")
LOGIN_REDIRECT_URL = "/management"
TWO_FACTOR_TOTP_DIGITS = 6
WSGI_APPLICATION = config("WSGI_APPLICATION","gdl.wsgi.application")
ASGI_APPLICATION = config("ASGI_APPLICATION","gdl.asgi.application")
TELEGRAM_API_TOKEN=config("TELEGRAM_API_TOKEN",None,)
TELEGRAM_VALIDATION_CODE_LENGTH=config("TELEGRAM_VALIDATION_CODE_LENGTH",8,cast=int)
GDL_USE_GPU=config("GDL_USE_GPU",True,cast=bool)
GDL_USE_MAX=config("GDL_USE_MAX",False,cast=bool)
GDL_USE_LOCAL_GPU=config("GDL_USE_LOCAL_GPU",False,cast=bool)
GDL_DAEMON_URI=config("GDL_DAEMON_URI","ws://127.0.0.1:9000")