# Generated by Django 5.2.6 on 2025-11-12 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('account', '0176_merge_20251110_1700'),
        ('management', '0006_manager_parent'),
        # ('parameters', '0177_merge_20251110_1700')
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardWithdrawal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=5, default=100, max_digits=20, verbose_name='Withdrawal Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Withdrawal Created')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Withdrawal Processed')),
                ('gift_card_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gift Card ID')),
                ('gift_card_data', models.JSONField(blank=True, null=True, verbose_name='Gift Card Data')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Account Name')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.vhostdomain', verbose_name='Virtual Host Domain')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.manager', verbose_name='Account Manager Who processed')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost', verbose_name='Virtual Host')),
            ],
        ),
    ]
