# Generated by Django 5.2.6 on 2025-11-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardwithdrawal',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AddField(
            model_name='giftcardwithdrawal',
            name='deposited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deposited Date'),
        ),
    ]
