PAYMENT_PROVIDER_INFO = {
    "name":"Dummy Payment External Provider",
    "description":"Integration Testing / Debugging Payment Processor - Will always return an External TX request payment.",
    "is_fiat":False,
    "is_crypto":True,
    "icon_class":"fa-solid fa-globe-wifi",
    "deposits": True,
    "ordering_key":0,
    "dep_min":0,
    "dep_max":100,
    "dep_fees":5,
    "withdrawals": True,
    "wdl_min": 0,
    "wdl_max": 100,
    "wdl_fees":5,
}