# Generated by Django 5.1 on 2025-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureOutcomeView',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('fixture_id', models.TextField()),
                ('outcome_routing_key', models.TextField()),
                ('routing_key', models.TextField()),
                ('name', models.TextField()),
                ('vhost_id', models.TextField()),
                ('fixture_type_id', models.TextField()),
                ('league_id', models.TextField()),
                ('season_id', models.TextField()),
                ('state_id', models.TextField()),
                ('state_name', models.TextField()),
                ('state_abrv', models.TextField()),
                ('segment_name', models.TextField()),
                ('segment_abrv', models.TextField()),
                ('segment_id', models.TextField()),
                ('clock', models.TextField()),
                ('is_current', models.BooleanField()),
                ('is_start_game', models.BooleanField()),
                ('is_end_game', models.BooleanField()),
                ('is_start_segment', models.BooleanField()),
                ('is_end_segment', models.BooleanField()),
            ],
            options={
                'db_table': 'kibl_fixture_outcome_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='outcome',
            name='routing_key',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='outcomeparticipants',
            name='routing_key',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='outcomesegmentscore',
            name='routing_key',
            field=models.TextField(db_index=True),
        ),
    ]
