# Generated by Django 5.1 on 2025-08-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0002_fixtureoutcomeview_alter_outcome_routing_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='routing_key',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixturemarket',
            name='routing_key',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixtureparticipants',
            name='routing_key',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='routing_key',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='outcomeparticipants',
            name='routing_key',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='outcomesegmentscore',
            name='routing_key',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
