# Generated by Django 5.1 on 2025-08-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0003_alter_fixture_routing_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiblio.state'),
        ),
    ]
