# Generated by Django 5.1 on 2025-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0004_fixture_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='fixture_id',
            field=models.IntegerField(unique=True),
        ),
    ]
