# Generated by Django 5.1 on 2025-09-25 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0005_alter_fixture_fixture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
