# Generated by Django 5.1 on 2025-11-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0006_fixture_created_at_fixture_updated_at'),
        ('parameters', '0182_vhostdomain_welcome_email_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sport_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='sport',
            unique_together={('vhost', 'sport_id')},
        ),
    ]
