# Generated by Django 5.1 on 2025-11-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0007_alter_sport_sport_id_alter_sport_unique_together'),
        ('parameters', '0183_alter_timezone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='fixture_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together={('vhost', 'fixture_id')},
        ),
    ]
