# Generated by Django 6.0.1 on 2026-01-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0008_alter_fixture_fixture_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixturemarket',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='fixturemarket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
