# Generated by Django 6.0.1 on 2026-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiblio', '0009_alter_fixturemarket_options_fixturemarket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='teams_morphed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='morphed',
            field=models.BooleanField(default=False),
        ),
    ]
