# Generated by Django 5.1 on 2025-09-21 22:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0001_initial'),
        ('parameters', '0059_alter_apperanceparameters_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='vhost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='at_event_type', to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='vhost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='at_tournament', to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('player_key', models.TextField(db_index=True)),
                ('player_name', models.TextField()),
                ('player_country', models.TextField()),
                ('player_bday', models.DateField()),
                ('player_logo', models.TextField()),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_players', to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_key', models.TextField(db_index=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_status', models.TextField(blank=True, null=True)),
                ('tournament_round', models.TextField(blank=True, null=True)),
                ('tournament_season', models.TextField(blank=True, null=True)),
                ('event_live', models.IntegerField(default=0)),
                ('event_qualification', models.BooleanField(default=False)),
                ('pointbypoint', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('event_type_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_fixture_type', to='apitennis.eventtype')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_fixture', to='apitennis.tournament')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_fixture', to='parameters.vhost')),
                ('event_first_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_fixture_first_player', to='apitennis.players')),
                ('event_second_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_fixture_second_player', to='apitennis.players')),
                ('event_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_fixture_winner', to='apitennis.players')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=4)),
                ('type', models.TextField()),
                ('rank', models.IntegerField()),
                ('titles', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('hard_won', models.IntegerField()),
                ('hard_lost', models.IntegerField()),
                ('clay_won', models.IntegerField()),
                ('clay_lost', models.IntegerField()),
                ('grass_won', models.IntegerField()),
                ('grass_lost', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitennis.players')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_playerstats', to='parameters.vhost')),
            ],
        ),
    ]
