# Generated by Django 5.1 on 2025-09-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0002_eventtype_vhost_tournament_vhost_players_fixture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='event_type_key',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_key',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
