# Generated by Django 5.1 on 2025-09-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0003_alter_eventtype_event_type_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_surface',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
