# Generated by Django 5.1 on 2025-09-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0004_tournament_tournament_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_surface',
            field=models.TextField(blank=True, null=True),
        ),
    ]
