# Generated by Django 5.1 on 2025-09-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0005_alter_tournament_tournament_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='event_key',
            field=models.IntegerField(db_index=True),
        ),
    ]
