# Generated by Django 5.1 on 2025-09-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0006_alter_fixture_event_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_bday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
