# Generated by Django 5.1 on 2025-09-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0007_alter_fixture_event_date_alter_fixture_event_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='event_type_type',
            new_name='event_type',
        ),
    ]
