# Generated by Django 5.1 on 2025-09-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0008_rename_event_type_type_fixture_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='event_qualification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
