# Generated by Django 5.1 on 2025-09-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0009_alter_fixture_event_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='statistics',
            field=models.JSONField(default=dict),
        ),
    ]
