# Generated by Django 5.1 on 2025-09-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0010_fixture_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='event_type_key',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
