# Generated by Django 5.1 on 2025-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0012_eventtype_inserted_on_eventtype_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_key',
            field=models.IntegerField(db_index=True),
        ),
    ]
