# Generated by Django 5.1 on 2025-09-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0013_alter_tournament_tournament_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
