# Generated by Django 5.1 on 2025-09-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0014_tournament_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
