# Generated by Django 5.2.6 on 2025-11-16 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0015_fixture_commence_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_fixture', to='apitennis.tournament'),
        ),
    ]
