# Generated by Django 5.2.6 on 2025-11-30 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0016_alter_fixture_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureView',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('event_key', models.IntegerField(db_index=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('commence_time', models.DateTimeField(blank=True, null=True)),
                ('event_status', models.TextField(blank=True, null=True)),
                ('tournament_round', models.TextField(blank=True, null=True)),
                ('tournament_season', models.TextField(blank=True, null=True)),
                ('event_live', models.IntegerField(default=0)),
                ('event_qualification', models.BooleanField(blank=True, default=False, null=True)),
                ('pointbypoint', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('statistics', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'apitennis_fixture_view',
                'managed': False,
            },
        ),
    ]
