# Generated by Django 6.0.1 on 2026-01-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitennis', '0017_fixtureview'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='_being_processed',
            field=models.BooleanField(default=False),
        ),
    ]
