# Generated by Django 5.2.8 on 2025-12-09 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryGame',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', models.CharField(help_text='State code (e.g., NY, CA)', max_length=2)),
                ('name', models.CharField(help_text='Display name (e.g., New York Lotto)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe identifier (e.g., ny-lotto)', unique=True)),
                ('url', models.URLField(help_text='Scrape target URL')),
                ('game_type', models.CharField(choices=[('pool', 'Pool'), ('positional', 'Positional'), ('bonus', 'Bonus')], default='pool', max_length=20)),
                ('main_count', models.IntegerField(help_text='Number of main numbers to pick')),
                ('main_range_min', models.IntegerField(default=1, help_text='Minimum value for main numbers')),
                ('main_range_max', models.IntegerField(help_text='Maximum value for main numbers')),
                ('bonus_count', models.IntegerField(default=0, help_text='Number of bonus numbers (0 if none)')),
                ('bonus_range_min', models.IntegerField(blank=True, help_text='Minimum value for bonus', null=True)),
                ('bonus_range_max', models.IntegerField(blank=True, help_text='Maximum value for bonus', null=True)),
                ('is_positional', models.BooleanField(default=False, help_text='True for positional games like Daily 4')),
                ('schedule', models.JSONField(default=dict, help_text='Draw schedule configuration')),
                ('selectors', models.JSONField(default=dict, help_text='CSS selectors for scraping')),
                ('parser_config', models.JSONField(default=dict, help_text='Parsing rules')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lottery Game',
                'verbose_name_plural': 'Lottery Games',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('draw_date', models.DateField(help_text='Date of the draw')),
                ('draw_datetime', models.DateTimeField(blank=True, help_text='Exact draw time if known', null=True)),
                ('draw_label', models.CharField(blank=True, choices=[('midday', 'Midday'), ('evening', 'Evening'), ('morning', 'Morning'), ('night', 'Night')], help_text='Label for multi-draw days (midday, evening, etc.)', max_length=20, null=True)),
                ('draw_number', models.CharField(blank=True, help_text='Official draw number if available', max_length=50, null=True)),
                ('main_numbers', models.JSONField(default=list, help_text='List of main winning numbers')),
                ('bonus_numbers', models.JSONField(default=list, help_text='List of bonus numbers (empty if none)')),
                ('raw_response', models.TextField(blank=True, default='', help_text='Scraped HTML for debugging')),
                ('scrape_success', models.BooleanField(default=True, help_text='Whether the scrape succeeded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='statelottery.lotterygame')),
            ],
            options={
                'verbose_name': 'Lottery Draw',
                'verbose_name_plural': 'Lottery Draws',
                'ordering': ['-draw_date', '-draw_datetime'],
                'unique_together': {('game', 'draw_date', 'draw_label')},
            },
        ),
        migrations.CreateModel(
            name='LotteryScrapeLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, help_text='When the scrape was attempted')),
                ('success', models.BooleanField(default=False, help_text='Whether the scrape succeeded')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if scrape failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retries before this attempt')),
                ('scrape_duration_ms', models.IntegerField(blank=True, help_text='Time taken to scrape in milliseconds', null=True)),
                ('screenshot_path', models.CharField(blank=True, default='', help_text='Path to failure screenshot if captured', max_length=500)),
                ('draw_found', models.ForeignKey(blank=True, help_text='The draw record created/found if successful', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_logs', to='statelottery.lotterydraw')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='statelottery.lotterygame')),
            ],
            options={
                'verbose_name': 'Scrape Log',
                'verbose_name_plural': 'Scrape Logs',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
