# Generated by Django 6.0.1 on 2026-01-21 04:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('acctnum', models.TextField(default='100100', unique=True, verbose_name='Account Number')),
                ('acctname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Your Name')),
                ('holder', models.TextField(blank=True, help_text='Optional, Account holder name.', null=True, verbose_name='Account Holder')),
                ('pronouns', models.TextField(blank=True, null=True, verbose_name='Your Pronouns')),
                ('fday', models.DateField(blank=True, null=True, verbose_name="Account Holder's Favourite Day")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/avatars/', verbose_name='Avatar Image:')),
                ('secret', models.CharField(editable=False, max_length=128)),
                ('secret_reminder', models.TextField(blank=True, null=True, verbose_name='Secret Reminder Question')),
                ('secret_answer', models.TextField(blank=True, null=True, verbose_name='Secret Answer Question')),
                ('phone_wager_pin', models.TextField(blank=True, null=True, verbose_name='Phone Wager Pin')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Account Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Account Updated')),
                ('activated', models.DateTimeField(blank=True, null=True, verbose_name='Account Activated At')),
                ('email1', models.EmailField(blank=True, help_text='Your account is identified by your email.', max_length=254, null=True, verbose_name='Email 1')),
                ('email2', models.EmailField(blank=True, help_text='Providing a secondary e-mail address is recommended for account recovery purposes! (Optional)', max_length=254, null=True, verbose_name='Email 2')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, verbose_name='Current Account Credit Limit')),
                ('low_balance_alert', models.DecimalField(decimal_places=5, default=1000, max_digits=20, verbose_name='The balance at which an alert is sent to the account')),
                ('min_wager', models.DecimalField(decimal_places=5, default=100, help_text='All wagers must be equal or greater than this value.', max_digits=20, verbose_name='Min Wager Amount')),
                ('max_wager', models.DecimalField(decimal_places=5, default=1000, help_text='All wagers must be equal or less than this value.', max_digits=20, verbose_name='Max Wager Amount')),
                ('wager_limit', models.DecimalField(decimal_places=5, default=10000, help_text='Maximum amount account can wager.', max_digits=20, verbose_name='Wager Limit')),
                ('mobile', models.TextField(blank=True, help_text='Your Mobile Number!', null=True, verbose_name='SMS/Mobile Number')),
                ('settle', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, verbose_name='Settle Balance at')),
                ('active', models.BooleanField(default=False, help_text='Is this Account active? (Global enable) - FALSE by default for self-registration validation.')),
                ('frozen', models.BooleanField(default=False, help_text='Is this Account Frozen/held?')),
                ('can_place_wagers', models.BooleanField(default=True, help_text='Can this account place online wagers?', verbose_name='Enable/Disable All Wagering')),
                ('can_place_phone_wagers', models.BooleanField(default=True, help_text='Can this account place phone wagers?', verbose_name='Enable Phone Wagers')),
                ('can_use_sportsbook', models.BooleanField(default=True, help_text='Enable Sportsbook for Acct', verbose_name='Enable Sportsbook')),
                ('must_change_pw', models.BooleanField(default=True)),
                ('use_rolling_balance', models.BooleanField(default=True, help_text='If enabled, the player balance will be rolled forward; without using the Settled balance amount.', verbose_name='Use Rolling Balance')),
                ('must_set_tz', models.BooleanField(default=True)),
                ('has_seen_intro_help', models.BooleanField(default=False)),
                ('agent_transfer_blocked', models.BooleanField(default=False, verbose_name='Restrict Agent Transfer for this Account')),
                ('available_invites', models.IntegerField(default=0, verbose_name='Available Invites')),
                ('rules_package', models.UUIDField(blank=True, null=True, verbose_name='Rules Package UUID')),
                ('sms_validated', models.BooleanField(default=False)),
                ('telegram_validated', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('view_all_accounts', 'Can view accounts from all users/agents'), ('bulk_deposit_operations', 'Can use the Bulk Deposit/Withdraw Operations Tool')],
            },
        ),
        migrations.CreateModel(
            name='AccountActivationTokens',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Token Created at')),
                ('expires', models.DateTimeField(verbose_name='Token Expires at')),
                ('key', models.TextField(verbose_name='Activation Token Key')),
            ],
        ),
        migrations.CreateModel(
            name='AccountEmailChanges',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Token Created at')),
                ('expires', models.DateTimeField(verbose_name='Token Expires at')),
                ('key', models.TextField(verbose_name='Activation Token Key')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now=True, verbose_name='Activated Date')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLockouts',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False, verbose_name='Lockout Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Token Expires at')),
                ('system', models.BooleanField(default=False, verbose_name='System Lockout')),
                ('self_lockout', models.BooleanField(default=False, verbose_name='Self Lockout')),
                ('notes', models.TextField(default='', verbose_name='Lockout Notes')),
            ],
        ),
    ]
