# Generated by Django 6.0.1 on 2026-01-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cashier.accountlevels', verbose_name='Account Level'),
        ),
    ]
