# Generated by Django 6.0.1 on 2026-01-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('cashier', '0001_initial'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.vhostdomain', verbose_name='Virtual Host Domain'),
        ),
        migrations.AddField(
            model_name='account',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.locales', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='account',
            name='system_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.theme', verbose_name='Game Skin'),
        ),
        migrations.AddField(
            model_name='account',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.timezone', verbose_name='Timezone'),
        ),
        migrations.AddField(
            model_name='account',
            name='vhost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost', verbose_name='Virtual Host'),
        ),
        migrations.AddField(
            model_name='accountactivationtokens',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='accountemailchanges',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AddField(
            model_name='accountlevelhistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.account', verbose_name='Account Level'),
        ),
        migrations.AddField(
            model_name='accountlevelhistory',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cashier.accountlevels', verbose_name='Account Level'),
        ),
        migrations.AddField(
            model_name='accountlockouts',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_lockouts', to='account.account', verbose_name='Account'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('email1__isnull', False)), fields=('vhost', 'email1'), name='unique_email1_per_vhost'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('email2__isnull', False)), fields=('vhost', 'email2'), name='unique_email2_per_vhost'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('acctname', 'vhost'), name='unique_acctname_per_vhost'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('acctname', 'vhost'), ('vhost', 'mobile')},
        ),
        migrations.AlterUniqueTogether(
            name='accountemailchanges',
            unique_together={('account', 'email1', 'email2')},
        ),
        migrations.AlterUniqueTogether(
            name='accountlevelhistory',
            unique_together={('account', 'level')},
        ),
    ]
