# Generated by Django 5.2.6 on 2025-12-02 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gid', models.IntegerField()),
                ('name', models.TextField()),
                ('id', models.IntegerField()),
                ('file_group', models.TextField()),
                ('iscup', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoccerFixture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('static_id', models.IntegerField(blank=True, null=True)),
                ('fixture_id', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('intj_time', models.TextField(blank=True, null=True)),
                ('intj_minute', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('formatted_date', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('venue', models.TextField(blank=True, null=True)),
                ('v_id', models.TextField(blank=True, null=True)),
                ('iscup', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.sportcategory')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='goalserve.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='goalserve.team')),
            ],
        ),
        migrations.CreateModel(
            name='SoccerFixtureScore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.soccerfixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='goalserve.team')),
            ],
        ),
        migrations.CreateModel(
            name='SoccerEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('minute', models.TextField(blank=True, null=True)),
                ('extra_min', models.TextField(blank=True, null=True)),
                ('player', models.TextField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('assist', models.TextField(blank=True, null=True)),
                ('assist_id', models.IntegerField(blank=True, null=True)),
                ('is_penalty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.soccerfixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.team')),
            ],
        ),
    ]
