# Generated by Django 5.2.6 on 2025-12-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportcategory',
            name='file_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='gid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='iscup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
