# Generated by Django 5.2.6 on 2025-12-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0002_alter_sportcategory_file_group_and_more'),
        ('parameters', '0183_alter_timezone_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccerevent',
            name='vhost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soccerfixture',
            name='vhost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soccerfixturescore',
            name='vhost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fixturescore', to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportcategory',
            name='vhost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parameters.vhost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='vhost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='goalservedteams', to='parameters.vhost'),
            preserve_default=False,
        ),
    ]
