# Generated by Django 5.2.6 on 2025-12-02 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0004_remove_soccerfixture_iscup_soccerevent_result'),
        ('parameters', '0183_alter_timezone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketBallFixture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('static_id', models.IntegerField(blank=True, null=True)),
                ('fixture_id', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketaway_team', to='goalserve.team')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.sportcategory')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskethome_team', to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketballfixture', to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='BasketBallScore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('q1', models.IntegerField(blank=True, default=0, null=True)),
                ('q2', models.IntegerField(blank=True, default=0, null=True)),
                ('q3', models.IntegerField(blank=True, default=0, null=True)),
                ('q4', models.IntegerField(blank=True, default=0, null=True)),
                ('ot', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.basketballfixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketscores', to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketballscore', to='parameters.vhost')),
            ],
        ),
    ]
