# Generated by Django 5.2.6 on 2025-12-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0005_basketballfixture_basketballscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballfixture',
            name='static_id',
        ),
    ]
