# Generated by Django 5.2.6 on 2025-12-02 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0006_remove_basketballfixture_static_id'),
        ('parameters', '0183_alter_timezone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBallFixture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fixture_id', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('extra_inn', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseaway_team', to='goalserve.team')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.sportcategory')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basehome_team', to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseballfixture', to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='BaseBallScore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('in1', models.IntegerField(blank=True, default=0, null=True)),
                ('in2', models.IntegerField(blank=True, default=0, null=True)),
                ('in3', models.IntegerField(blank=True, default=0, null=True)),
                ('in4', models.IntegerField(blank=True, default=0, null=True)),
                ('in5', models.IntegerField(blank=True, default=0, null=True)),
                ('in6', models.IntegerField(blank=True, default=0, null=True)),
                ('in7', models.IntegerField(blank=True, default=0, null=True)),
                ('in8', models.IntegerField(blank=True, default=0, null=True)),
                ('in9', models.IntegerField(blank=True, default=0, null=True)),
                ('extra', models.TextField(blank=True, default=0, null=True)),
                ('hits', models.IntegerField(blank=True, default=0, null=True)),
                ('errors', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.baseballfixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basescores', to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseballscore', to='parameters.vhost')),
            ],
        ),
    ]
