# Generated by Django 5.2.6 on 2025-12-02 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0007_baseballfixture_baseballscore'),
        ('parameters', '0183_alter_timezone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisFixture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fixture_id', models.IntegerField(blank=True, null=True)),
                ('tb', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tennis_away', to='goalserve.team')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.sportcategory')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tennis_home', to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tennisfixture', to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='TennisScore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('q1', models.IntegerField(blank=True, default=0, null=True)),
                ('q2', models.IntegerField(blank=True, default=0, null=True)),
                ('q3', models.IntegerField(blank=True, default=0, null=True)),
                ('q4', models.IntegerField(blank=True, default=0, null=True)),
                ('s5', models.IntegerField(blank=True, default=0, null=True)),
                ('serve', models.IntegerField(blank=True, default=0, null=True)),
                ('winner', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.tennisfixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tennisscore', to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tennisscore', to='parameters.vhost')),
            ],
        ),
    ]
