# Generated by Django 5.2.6 on 2025-12-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0008_tennisfixture_tennisscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tennisscore',
            old_name='q1',
            new_name='s1',
        ),
        migrations.RenameField(
            model_name='tennisscore',
            old_name='q2',
            new_name='s2',
        ),
        migrations.RenameField(
            model_name='tennisscore',
            old_name='q3',
            new_name='s3',
        ),
        migrations.RenameField(
            model_name='tennisscore',
            old_name='q4',
            new_name='s4',
        ),
    ]
