# Generated by Django 5.2.6 on 2025-12-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0009_rename_q1_tennisscore_s1_rename_q2_tennisscore_s2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisscore',
            name='game_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
