# Generated by Django 5.2.6 on 2025-12-03 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0010_tennisscore_game_score'),
        ('parameters', '0183_alter_timezone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HockeyFixture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('static_id', models.IntegerField(blank=True, null=True)),
                ('fixture_id', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('intj_time', models.TextField(blank=True, null=True)),
                ('intj_minute', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('formatted_date', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('venue', models.TextField(blank=True, null=True)),
                ('v_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hockey_away_team', to='goalserve.team')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.sportcategory')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hockey_home_team', to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hockeyfixture', to='parameters.vhost')),
            ],
        ),
        migrations.CreateModel(
            name='HockeyEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('minute', models.TextField(blank=True, null=True)),
                ('extra_min', models.TextField(blank=True, null=True)),
                ('player', models.TextField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('assist', models.TextField(blank=True, null=True)),
                ('assist_id', models.IntegerField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('is_penalty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hockeyevents', to='parameters.vhost')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.hockeyfixture')),
            ],
        ),
        migrations.CreateModel(
            name='HockeyFixtureScore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalserve.hockeyfixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hockey_scores', to='goalserve.team')),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hockeyscore', to='parameters.vhost')),
            ],
        ),
    ]
