# Generated by Django 5.2.6 on 2025-12-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0011_hockeyfixture_hockeyevent_hockeyfixturescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hockeyfixture',
            name='formatted_date',
        ),
        migrations.RemoveField(
            model_name='hockeyfixture',
            name='intj_minute',
        ),
        migrations.RemoveField(
            model_name='hockeyfixture',
            name='intj_time',
        ),
        migrations.RemoveField(
            model_name='hockeyfixture',
            name='static_id',
        ),
        migrations.RemoveField(
            model_name='hockeyfixture',
            name='v_id',
        ),
        migrations.RemoveField(
            model_name='hockeyfixture',
            name='venue',
        ),
        migrations.AddField(
            model_name='hockeyevent',
            name='period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hockeyfixture',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hockeyfixture',
            name='timer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hockeyfixturescore',
            name='first',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hockeyfixturescore',
            name='overtime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hockeyfixturescore',
            name='penalty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hockeyfixturescore',
            name='second',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hockeyfixturescore',
            name='third',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hockeyevent',
            name='assist_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
