# Generated by Django 5.2.6 on 2025-12-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0013_americanfballfixture_americanfballscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='americanfballfixture',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='americanfballfixture',
            name='timer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='americanfballfixture',
            name='venue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='americanfballfixture',
            name='venue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
