# Generated by Django 5.2.6 on 2025-12-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0014_americanfballfixture_commence_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='americanfballfixture',
            name='venue_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
