# Generated by Django 5.2.6 on 2025-12-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0015_alter_americanfballfixture_venue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisfixture',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
