# Generated by Django 5.2.6 on 2025-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0016_tennisfixture_commence_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisscore',
            name='game_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tennisscore',
            name='s1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tennisscore',
            name='s2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tennisscore',
            name='s3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tennisscore',
            name='s4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tennisscore',
            name='s5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tennisscore',
            name='serve',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
