# Generated by Django 5.2.6 on 2025-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0017_alter_tennisscore_game_score_alter_tennisscore_s1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballfixture',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketballfixture',
            name='timer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
