# Generated by Django 5.2.6 on 2025-12-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalserve', '0018_basketballfixture_commence_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballfixture',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hockeyfixture',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soccerfixture',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
